---
- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present
  when: ansible_os_family == 'RedHat'

- name: start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_os_family  == 'RedHat'

- name: Allow http port on Debian
  community.general.ufw:
    rule: allow
    name: 'Nginx HTTP'
  when: ansible_os_family == 'Debian'

- name: Allow http port on RHEL8
  ansible.posix.firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
  when: ansible_os_family == 'RedHat'

- name: Restart Firewalld on RHEL8
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
  changed_when: false
  when: ansible_os_family == 'RedHat'

