---
nginx_daemon: nginx
php_fpm_daemon: php-fpm 
php_fpm_socket: /var/run/php-fpm/www.sock
nginx_config_path: /etc/nginx/nginx.conf
nginx_wp_config_path: /etc/nginx/conf.d/wordpress.conf
nginx_user: nginx
nginx_package: nginx
php_packages:
  - php
  - php-fpm
  - php-mysqlnd
  - php-cli
  - php-json
  - php-gd
  - php-mbstring
  - php-pdo
  - php-xml
  - php-pecl-zip
php_fpm_config: /etc/php-fpm.d/www.conf

