---
- include_tasks: variables.yml

- name: Ensure that zabbix-agent is installed on Debian based OS
  ansible.builtin.apt:
    name: zabbix-agent
    state: present
  when: ansible_os_family == 'Debian'

- name: Install zabbix repo
  ansible.builtin.dnf:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present
    disable_gpg_check: True
  when: ansible_os_family == 'RedHat'

- name: Ensure that zabbix-agent is installed on RHEL8 based OS
  ansible.builtin.dnf:
    name: zabbix-agent
    state: present
  when: ansible_os_family == 'RedHat'

- name: Use config template
  ansible.builtin.template:
    src: "{{ zabbix_agentd_template }}"
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644

- include_tasks: firewall.yml

- name: Ensure zabbix-agent service is started and enabled
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes
  changed_when: false

