---
- include_tasks: variables.yml

- name: Add the user "{{ username }}" with a primary group of 'wheel'
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password }}"
    state: present
    shell: /bin/bash
    groups: "{{ sudogroup }}"

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', pubkey_path) }}"

