---
- include_tasks: variables.yml

- include_tasks: Setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: Setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: configure.yml


